name: Manual trigger

on: 
  workflow_dispatch:
      inputs:
        version:
          description: version branch
          default: v1.0.0
          required: true
          
jobs:

  build:
    name: Rebuild
    runs-on: ubuntu-latest
    
    #Etapas
    steps:
    
        # 1 etapa - Efetuar o checkout da aplicação
      - name: checkout
        uses: actions/checkout@v3
        
        # 2 etapa - Instalar o SDK do dotnet
      - name: Setup .NET Core SDK dotnet-version 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
        # 3 etapa - Instalar dependencias do dotnet
      - name: Install dependencies
        run: dotnet restore
        
        # 4 etapa - Efetuar build da aplicação
      - name: BuildApplication
        run: dotnet build --configuration Release --no-restore
        
        # 5 etapa - Efetuar test da aplicação
      - name: test
        run: dotnet test --no-restore --verbosity normal
        
        
